name: Arduino_CI
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "examples/**"
      - "src/**"
      - ".github/workflows/arduino_ci.yml"
      - ".github/scripts/check_ci_json.py"
jobs:
  Arduino-Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board:
          - tlora_pager
          - twatch_ultra
          - twatchs3
        base_examples:
          - ble/BLEKeyboard/BLEKeyboard.ino
          - ble/BLEMouse/BLEMouse.ino
          - factory/factory.ino
          - helloworld/helloworld.ino

          - lvgl/benchmark/benchmark.ino
          - lvgl/event/event.ino
          - lvgl/get_started/get_started.ino
          - lvgl/layouts/flex/flex.ino
          - lvgl/layouts/grid/grid.ino
          - lvgl/scroll/scroll.ino
          - lvgl/style/style.ino
          - lvgl/third_party/gif/gif.ino
          - lvgl/third_party/image/image.ino
          - lvgl/widgets/animimg/animimg.ino
          - lvgl/widgets/arc/arc.ino
          - lvgl/widgets/bar/bar.ino
          - lvgl/widgets/btn/btn.ino
          - lvgl/widgets/btnmatrix/btnmatrix.ino
          - lvgl/widgets/calendar/calendar.ino
          - lvgl/widgets/canvas/canvas.ino
          - lvgl/widgets/chart/chart.ino
          - lvgl/widgets/checkbox/checkbox.ino
          - lvgl/widgets/dropdown/dropdown.ino
          - lvgl/widgets/img/img.ino
          - lvgl/widgets/imgbtn/imgbtn.ino
          - lvgl/widgets/keyboard/keyboard.ino
          - lvgl/widgets/label/label.ino
          - lvgl/widgets/led/led.ino
          - lvgl/widgets/line/line.ino
          - lvgl/widgets/list/list.ino
          - lvgl/widgets/menu/menu.ino
          - lvgl/widgets/msgbox/msgbox.ino
          - lvgl/widgets/obj/obj.ino
          - lvgl/widgets/roller/roller.ino
          - lvgl/widgets/scale/scale.ino
          - lvgl/widgets/slider/slider.ino
          - lvgl/widgets/span/span.ino
          - lvgl/widgets/spinbox/spinbox.ino
          - lvgl/widgets/spinner/spinner.ino
          - lvgl/widgets/switch/switch.ino
          - lvgl/widgets/table/table.ino
          - lvgl/widgets/tabview/tabview.ino
          - lvgl/widgets/textarea/textarea.ino
          - lvgl/widgets/tileview/tileview.ino
          - lvgl/widgets/win/win.ino

          - peripheral/DisplayBrightness/DisplayBrightness.ino
          - peripheral/DisplayRotation/DisplayRotation.ino
          - peripheral/GPSFactory/GPSFactory.ino
          - peripheral/GPSFullExample/GPSFullExample.ino
          - peripheral/IRsendDemo/IRsendDemo.ino
          - peripheral/Keyboard/Keyboard.ino
          - peripheral/NFC_Reader/NFC_Reader.ino
          - peripheral/PlayMusicFromPROGMEM/PlayMusicFromPROGMEM.ino
          - peripheral/PlayMusicFromSDCard/PlayMusicFromSDCard.ino
          - peripheral/playWAV/playWAV.ino
          - peripheral/RecordWAV/RecordWAV.ino
          - peripheral/RTC_AlarmByUnits/RTC_AlarmByUnits.ino
          - peripheral/RTC_TimeLib/RTC_TimeLib.ino
          - peripheral/RTC_TimeSynchronization/RTC_TimeSynchronization.ino
          - peripheral/SD_Speed/SD_Speed.ino
          - peripheral/SD_Test/SD_Test.ino
          - peripheral/SD_time/SD_time.ino
          - peripheral/SimpleTone/SimpleTone.ino
          - peripheral/Vibrate_Basic/Vibrate_Basic.ino

          - power/GaugeExample/GaugeExample.ino
          - power/PowerManageEvent/PowerManageEvent.ino
          - power/PowerManageMonitor/PowerManageMonitor.ino

          - radio/LR1121/LR11x0_Receive/LR11x0_Receive.ino
          - radio/LR1121/LR11x0_Transmit/LR11x0_Transmit.ino

          - radio/nRF2401/nRF24_Receive/nRF24_Receive.ino
          - radio/nRF2401/nRF24_Transmit/nRF24_Transmit.ino

          - radio/SI4432/Si4432_Receive/Si4432_Receive.ino
          - radio/SI4432/Si4432_Transmit/Si4432_Transmit.ino

          - radio/SX1262/LoRaWAN/LoRaWAN.ino
          - radio/SX1262/SX126x_PingPong/SX126x_PingPong.ino
          - radio/SX1262/SX126x_Receive/SX126x_Receive.ino
          - radio/SX1262/SX126x_Transmit/SX126x_Transmit.ino

          - radio/SX1280/SX128x_Ranging/SX128x_Ranging.ino
          - radio/SX1280/SX128x_Receive/SX128x_Receive.ino
          - radio/SX1280/SX128x_Transmit/SX128x_Transmit.ino

          - sensor/BHI260AP_6DoF/BHI260AP_6DoF.ino
          - sensor/BHI260AP_Euler/BHI260AP_Euler.ino
          - sensor/BMA423_Accelerometer/BMA423_Accelerometer.ino
          - sensor/BMA423_Feature/BMA423_Feature.ino
          - sensor/BMA423_Temperature/BMA423_Temperature.ino

          - sleep/LightSleep/LightSleep.ino
          - sleep/WakeUpFromBootButton/WakeUpFromBootButton.ino
          - sleep/WakeUpFromPowerButton/WakeUpFromPowerButton.ino
          - sleep/WakeUpFromSensor/WakeUpFromSensor.ino
          - sleep/WakeUpFromTimer/WakeUpFromTimer.ino
          - sleep/WakeUpFromTouchPanel/WakeUpFromTouchPanel.ino

    env:
      SKETCH: ${{matrix.base_examples}}
      LILYGO_BOARD_TYPE: ${{matrix.board}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Arduino Ci
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz -O arduino-cli.tar.gz
          sudo tar xf arduino-cli.tar.gz -C /usr/local/bin arduino-cli
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_dev_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Check ci.json
        id: check_json
        run: |
          python .github/scripts/check_ci_json.py \
            --dir-path "$PWD/examples/$(dirname "$SKETCH")" \
            --board "$LILYGO_BOARD_TYPE"
      
      - name: Build examples
        if: steps.check_json.outputs.should_build == 'true'
        run: |
          cd $GITHUB_WORKSPACE

          mkdir -p $HOME/Arduino/libraries ;
          cd $HOME/Arduino/libraries ;
          git clone https://github.com/Xinyuan-LilyGO/LilyGoLib-ThirdParty.git $HOME/Arduino/libraries ;

          DIR_PATH=$(dirname "$PWD/examples/$SKETCH")
          echo "RUN EXAMPLE PATH:"$DIR_PATH
          echo "ACTIVE RADIO: ${{ steps.check_json.outputs.active_radio }}"
          echo "SHOULD BUILD: ${{ steps.check_json.outputs.should_build }}"
          
          if [[ "${{ steps.check_json.outputs.should_build }}" == "true" ]]; then
            arduino-cli compile \
            -besp32:esp32:$LILYGO_BOARD_TYPE:UploadSpeed=921600,USBMode=hwcdc,CDCOnBoot=cdc,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,PartitionScheme=app3M_fat9M_16MB,DebugLevel=none,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=default,Revision=${{ steps.check_json.outputs.active_radio }} \
              --library . \
              $PWD/examples/$SKETCH
          else
            echo "Skip the compilation step according to the ci.json configuration"
            exit 0
          fi    
